Translate higher order components to uzbek language
reactjs/uz.reactjs.org pull request #44
Opened 2020-09-06 07:07 UTC by doston92

2021-03-02 13:39 UTC, doniyor2109 requested changes

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Yuqori darajadagi komponent (HOC) - bu mantiqni qayta ishlatishning ilg'or usullaridan biri. HOClar React API-ning bir qismi emas, lekin ko'pincha tarkibiy qismlarning kompozitsion xususiyati tufayli
```suggestion
Yuqori darajadagi komponent (HOC) - bu komponent mantiqni qayta ishlatishning ilg'or usullaridan biri. HOClar React API-ning bir qismi emas. Ular Reactning kompozitsion xususiyatidan hosil bo'lgandir.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Agar oddiy komponent rekvizitlarni UI ga aylantirsa, unda yuqori darajadagi komponent komponentni boshqa komponentga o'zgartiradi.
```suggestion
Agar oddiy komponent propsni UI ga aylantirsa, unda yuqori darajadagi komponent komponentni boshqa komponentga o'zgartiradi.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +HOC ko'pincha Redux-da [`connect`](https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#connect) va Relay-da [`createFragmentContainer`](http://facebook.github.io/relay/docs/en/frag
```suggestion
HOC ko'pincha uchinchi tomon kutubxonalarida uchraydi. Misol uchun: Reduxning [`connect`](https://github.com/reduxjs/react-redux/blob/master/docs/api/connect.md#connect) funktsiyasi va Relayning [`createFragmentContainer`](http://facebook.github.io/relay/docs/en/fragment-container.html) funktsiyasi.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +> Ilgari biz aralashtirish funktsiyasini amalga oshirish uchun miksinlarni tavsiya qilgan edik, ammo vaqt o'tishi bilan ular foydadan ko'ra ko'proq zarar yetkazishini aniqladik. Nima uchun aralashmal
```suggestion
> Ilgari biz aralashtirish funktsiyasini amalga oshirish uchun miksinlarni tavsiya qilgan edik, ammo vaqt o'tishi bilan ular foydadan ko'ra ko'proq zarar yetkazishini aniqladik. Nima uchun miksinlarni olib tashlashga qaror qilganimizni va qanday qilib eski qismlarni qayta yozishni [bilib oling](/blog/2016/07/13/mixins-considered-harmful.html).
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +    // Ogohlantirishlarga obuna bo'lish
```suggestion
    // O'zgarishlarga obuna bo'lish
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +    // Sharhlarni state ga o'zlashtirish
```suggestion
    // Ma'lumotlar manbaasi o'zgarganda, komponent stateni yangilash
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Endi biz ma'lum bir nashrdagi o'zgarishlarni kuzatadigan va biz bilgan namunani takrorlaydigan yangi komponentni yaratamiz:
```suggestion
Endi biz oldingi komponentga oxshagan, ma'lum bir nashrdagi o'zgarishlarni kuzatadigan yangi komponentni yaratamiz:
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +`CommentList` va `BlogPost` o'rtasidagi farq shundaki, ular turli xil DataSource usullarini chaqirishadi va har xil natijalarni berishadi. Biroq, aksariyat hollarda ular o'xshash:
```suggestion
`CommentList` va `BlogPost` o'rtasidagi farq shundaki, ular turli xil DataSource funktsiyalarini chaqirishadi va har xil natijalarni berishadi. Biroq, ko'p hollarda ular o'xshash:
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Keling, `withSubscription` funktsiyasini amalga oshiraylik - u tarkibiy qismlarni yaratadi va ularni DataSource yangilanishlariga obuna qiladi (masalan, `CommentList` va `BlogPost`). Funktsiya o'ralg
```suggestion
Keling, `withSubscription` funktsiyasini amalga oshiraylik - u yangi komponent yaratadi va uni DataSource yangilanishlariga obuna qiladi (masalan, `CommentList` va `BlogPost`). Funktsiya komponentni qabul qiladi va `props`lar orqali yangi ma'lumotlarni uzatadi:
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +`CommentListWithSubscription` va `BlogPost Subscription` ko'rsatilganda, `CommentList` va `Blog Post` `DataSource`dan olingan eng so'nggi ma'lumotlarni `data` orqali uzatadi.:
```suggestion
`CommentListWithSubscription` va `BlogPost Subscription` ko'rsatilganda, `CommentList` va `Blog Post` `DataSource`dan olingan eng so'nggi ma'lumotlarni `data` prop orqali uzatadi.:
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Shuni esda tutingki, HOC hech narsani o'zgartirmaydi va o'ralgan komponentning xatti-harakatini meros qilib olmaydi, aksincha HOC tarkibidagi asl komponentni konteynerga o'raydi. HOC noaniq ta'sirga
```suggestion
Shuni esda tutingki, HOC berilgan komponentni o'zgartirmaydi va uning xatti-harakatini meros qilib olmaydi, aksincha HOC tarkibidagi asl komponentni konteynerga o'raydi. HOC noaniq ta'sirga ega bo'lgan sof funktsiyadir.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Hammasi shu! Qaytariladigan komponent konteynerga yuborilgan barcha `props`larni, shuningdek, `prop` ma'lumotlarini oladi. HOC uchun ma'lumotlarning qanday ishlatilishi muhim emas va aylantirilgan ko
```suggestion
Hammasi shu! Qaytariladigan komponent konteynerga yuborilgan barcha `props`larni, shuningdek, `data` propni oladi. HOC uchun ma'lumotlarning qanday ishlatilishi muhim emas va berligan komponent qayerdan malumot kelishi haqida o'ylamaydi.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +`WithSubscription` muntazam funktsiyasi bo'lgani uchun, biz istalgan miqdordagi argumentlarni olib tashlashimiz yoki qo'shishimiz mumkin. Masalan, biz `data` nomini sozlanishi va HOCni o'ralgan kompo
```suggestion
`withSubscription` oddiy funktsiyasi bo'lgani uchun, biz istalgan miqdordagi argumentlarni olib tashlashimiz yoki qo'shishimiz mumkin. Masalan, biz `data` nomini sozlanishi va HOCni o'ralgan komponentdan ajratib qo'yishimiz uchun. Biz shuningdek, `shouldComponentUpdate` yoki ma'lumotlar manbai konfiguratsiyasi uchun argument qo'sha olamiz. Bularning barchasi mumkin, chunki HOC komponentlarni yaratish jarayonini to'liq nazorat qiladi.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +`WithSubscription` va o'ralgan komponent o'rtasidagi aloqa, xuddi oddiy komponentlar kabi rekvizitlar yordamida amalga oshiriladi. Shu tufayli, bir xil rekvizitlarni o'ralgan komponentga o'tkazib yub
```suggestion
`withSubscription` va o'ralgan komponent o'rtasidagi aloqa, xuddi oddiy komponentlar kabi proplar yordamida amalga oshiriladi. Shu tufayli, bir xil proplarni o'ralgan komponentga o'tkazib yuborish sharti bilan, biz bir HOCni boshqasiga osongina almashtirishimiz mumkin. Bu, masalan, ma'lumot olish kutubxonasini o'zgartirishga qaror qilsak foydali bo'lishi mumkin.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +## O'ralgan komponentning mutatsiyasini qilmang. Kompozitsiyadan foydalaning. {#dont-mutate-the-original-component-use-composition}
```suggestion
## O'ralgan komponentning mutatsiya qilmang. Kompozitsiyadan foydalaning. {#dont-mutate-the-original-component-use-composition}
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +HOC tarkibidagi komponentning prototipini o'zgartirishga (yoki boshqa usul bilan mutatsiyaga) o'zgartirish vasvasasiga tushmang.
```suggestion
HOC tarkibidagi komponentning prototipini o'zgartirmang (yoki mutatsiya qilmang) .
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +  // Agar biz o'ralgan komponentni qaytaradigan bo'lsak, ehtimol biz uni o'zgartirdik.
```suggestion
  // Biz berilgan komponentni mutatsiya qilib qaytaryabmiz.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +// EnhancedComponent rekvizit o'zgarganda konsolga bosib chiqaradi
```suggestion
// EnhancedComponent prop lar o'zgarganda konsolga bosib chiqaradi
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Yuqoridagi misolda biz `InputComponent`ni `EnhancedComponent`dan tashqari qayta ishlata olmaymiz. Eng muhimi, agar biz `EnhancedComponent`ni boshqa HOC-ga o'rashni xohlasak, u tarkibiyDidUpdate-ni o'
```suggestion
Yuqoridagi misolda biz `InputComponent`ni `EnhancedComponent`dan tashqari qayta ishlata olmaymiz. Eng muhimi, agar biz `EnhancedComponent`ni boshqa HOC-ga o'rashni xohlasak, u tarkibiy `componentDidUpdate` ni o'zgartiradi, biz birinchi HOC tomonidan belgilangan funktsiyalarni o'chirib tashlaymiz! Bundan tashqari, `EnhancedComponent` funktsional komponentlar bilan ishlamaydi, chunki ular `componentDidUpdate` bilan ishlamaydi.
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +Mutatsiyaning o'rniga yuqori darajadagi komponentlar tarkibni idishga o'rash orqali kompozitsiyani qo'llashlari kerak:
```suggestion
Mutatsiyaning o'rniga yuqori darajadagi komponentlar berligan komponent konteyner komponent bilan o'rash orqali kompozitsiyani qo'llashlari kerak:
```

2021-03-02 13:39 UTC, doniyor2109 commented on content/docs/higher-order-components.md
> +      // Biz tarkibiy qismni mutatsiyalarsiz idishga o'rab olamiz. Super!
```suggestion
      // Biz berligan komponentni mutatsiyalarsiz konteynerga o'rab olamiz. Super!
```

2021-03-02 13:42 UTC, doniyor2109 commented
@doston92 Yordamingiz uchun katta Rahmat. Bir nechta komentariylar qoldirdim. Vaqtingiz bo'lganda ko'rib chiqarsiz. 
O'zgarishlar juda ko'p ekan. Qo'lgan qismini, yana ko'rib chiqamiz.

2021-04-06 10:14 UTC, 0tabek16 commented on content/docs/higher-order-components.md
> +      // Biz tarkibiy qismni mutatsiyalarsiz idishga o'rab olamiz. Super!
"mutatsiya"ni "oʻzgarish" deb tarjima qilish maqsadga muofiq boʻlar edi nazarimda.

2021-06-01 22:57 UTC, umidbekk approved these changes

2021-06-01 23:00 UTC, merged