Add jsx intro translation
reactjs/uz.reactjs.org pull request #54
Opened 2021-06-01 20:16 UTC by zrakhimov

Hello,

Translated "Introducing JSX" page into Uzbek. Please review

@umidbekk Not sure who else is actively reviewing, but mentioning you here

Let me know if any issues

Cheers!

Zokir

![Screenshot at Jun 01 16-13-13](https://user-images.githubusercontent.com/22464933/120384593-5c394d00-c2f4-11eb-8468-9d3092dba975.png)

2021-06-01 23:03 UTC, umidbekk commented
@doniyor2109 help to review pls 🙏

2021-06-02 06:24 UTC, doniyor2109 requested changes

2021-06-02 06:24 UTC, doniyor2109 commented on content/docs/introducing-jsx.md
> +>Biz yoqtirgan redaktoringizda ES6 va JSX kod to'g'ri yoritilishi uchun [Babel](https://babeljs.io/docs/en/next/editors) bilan sozlashingizni maslahat beramiz.
```suggestion
>Siz yoqtirgan redaktoringizda ES6 va JSX kod to'g'ri yoritilishi uchun [Babel](https://babeljs.io/docs/en/next/editors) bilan sozlashingizni maslahat beramiz.
```

2021-06-02 06:24 UTC, doniyor2109 commented on content/docs/introducing-jsx.md
> +JSX React "elementlari" ni hosil qiladi. Biz ularni DOM ga chizishni [keyingi bo'limda](/docs/rendering-elements.html) ko'rib chiqamiz. Quyida, siz boshlashingiz uchun kerak bo'ladigan JSX ning asosl
```suggestion
JSX React "elementlari" ni hosil qiladi. Biz ularni DOM ga chizishni [keyingi bo'limda](/docs/rendering-elements.html) ko'rib chiqamiz. Quyida, siz boshlashingiz uchun kerak bo'ladigan JSX ning asoslari bilan tanishib chiqishingiz mumkin.
```

2021-06-02 06:24 UTC, doniyor2109 commented on content/docs/introducing-jsx.md
> +title: JSX Kirish
```suggestion
title: JSX ga kirish
```

2021-06-02 12:20 UTC, umidbekk commented
@zrakhimov thanks for the PR! please check comments from @doniyor2109 regarding the grammar (I can't tell whether they should be merged or not)

2021-06-02 13:01 UTC, zrakhimov commented on content/docs/introducing-jsx.md
> +>Biz yoqtirgan redaktoringizda ES6 va JSX kod to'g'ri yoritilishi uchun [Babel](https://babeljs.io/docs/en/next/editors) bilan sozlashingizni maslahat beramiz.
agree

2021-06-02 13:03 UTC, zrakhimov commented on content/docs/introducing-jsx.md
> +title: JSX Kirish
Fair enough

2021-06-02 13:05 UTC, zrakhimov commented
@umidbekk @doniyor2109  thanks guys! feel free to let me know if any issues. I've accepted the suggestion

2021-06-02 13:36 UTC, umidbekk approved these changes
thank you for the contribution 🎉

2021-06-02 13:36 UTC, merged

2021-06-02 13:54 UTC, zrakhimov commented
@umidbekk I think you missed adding github username beside the topic/PR# on the issue page?

2021-06-02 14:12 UTC, umidbekk commented
> @umidbekk I think you missed adding github username beside the topic/PR# on the issue page?

Thanks! fixed it