Rendering Elements
reactjs/uz.reactjs.org pull request #55
Opened 2021-06-06 17:59 UTC by zrakhimov

Hey 👋

Translated "Rendering Elements" section. 

Please review and let me know if any issues

Cheers 🚀

![image](https://user-images.githubusercontent.com/22464933/120935082-1521d200-c6cf-11eb-9d66-af64fe26f9a0.png)

2021-06-07 09:11 UTC, 0tabek16 reviewed
Barcha yozgan narsalarim shaxsiy fikrimdan kelib chiqib yozildi. Fikrimga qoʻshilmaslikka toʻla haqqingiz bor.

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +Brauzer DOM elementlaridan farqli o'laroq, React elementlari oddiy obyektlar hisoblanadi va ularni yaratish juda arzonga tushadi. React DOM esa DOM ni React elementlariga mos ravishda yangilashni o'z
`cheap` deganda React jamoasi `resurslarni kam ishlatadigan` demoqchi, bu jumlani oʻzbek tiliga toʻgʻridan toʻgʻri tarjima qilish maqsadga muofiq deb oʻylamayman.

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +## Elementni DOM ga Chizish {#rendering-an-element-into-the-dom}
Chizish kichich harf bilan boshlanishi kerak.

P/S: Shaxsiy fikrim, qisqartmalardan keyin boʻsh joy tashlamasdan ketsak yaxshiroq emasmi?

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +Buni biz "ildiz" DOM tugunimiz deb ataymiz, chunki ichidagi hamma narsa React DOM orqali boshqariladi.
`DOM tugunimiz` tushinarsiz boʻlib qolmayaptimi? `Asosiy/Oʻzak DOM elementi` deb tarjima qilishni taklif qilgan boʻlardim.

Chunki `DOM node` deb `DOM Element` nazarda tutilyapti nazarimda.

P/S: ushbu atamani boshqa joylarda qoʻllanishlarini ham nazarda tutilgan

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +React bilan qurilgan ilovalar odatda faqat bir dona ildiz DOM tuguni bo'ladi. Agar siz React ni boshqa ishlab turgan ilovaga biriktirmoqchi bo'lsangiz, siz bir nechta ildiz DOM tugunlarini yaratishin
`isolated root DOM nodes` jumlasi tarjima paytida toʻliq ochib berilmagan nazarimda

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +React elementlari [o'zgarmas](https://en.wikipedia.org/wiki/Immutable_object) hisoblanadi. Bir marta yaratilgandan keyin, uni bolalari yoki atributlarini o'zgartirolmaysiz. Element kino lentasigadagi
`rasm` oʻrniga `kadr` soʻzini ishlatgan boʻlardim.

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +Bu misol [`ReactDOM.render()`](/docs/react-dom.html#render) ni har sekundda [`setInterval()`](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setInterval) kolbek orqali chaqiradi.
sekund -> soniya

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +>React ilovalari amalda [`ReactDOM.render()`](/docs/react-dom.html#render)ni faqat bir marta chaqiradi. Keyingi bo'limlarda shunday kod qanday qilib [holatli komponent](/docs/state-and-lifecycle.html
```suggestion
>React ilovalari amalda [`ReactDOM.render()`](/docs/react-dom.html#render)ni faqat bir marta chaqiradi. Keyingi bo'limlarda shunday kodni qanday qilib [holatli komponent](/docs/state-and-lifecycle.html)lar orqali yozishni oʻrganamiz.
```

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +## React Faqat Zarur Narsalarni Yangilaydi {#react-only-updates-whats-necessary}
```suggestion
## React faqat zarur narsalarni yangilaydi {#react-only-updates-whats-necessary}
```

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +Har bir sekundda biz butun bir UI daraxtini tasvirlaydigan element hosil qilishimizga qaramasdan, faqatgina matn tuguni o'zgargani tufayli React DOM shunga yarasha uni yangilaydi.
```suggestion
Har bir sekundda biz butun bir UI daraxtini tasvirlaydigan element hosil qilishimizga qaramasdan, React DOM faqatgina oʻzgargan matnli elementlarnigina yangilaydi.
```

2021-06-07 09:11 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +Bizning tajribamizda, ayni vaqt davomida UI ni qanday qilib o'zgartirish haqida o'ylashdan ko'ra, ayni vaqtda UI qanday ko'rinishga ega bo'lishi kerakligi haqida o'ylash, anchagina xatolarni bartaraf
```suggestion
Tajribamizdan kelib chiqib aytish mumkinki, UIʼni qanday qilib o'zgartirishdan ko'ra, UI qanday ko'rinishga ega bo'lishi kerakligi haqida o'ylash, anchagina xatolarni bartaraf qiladi.
```

2021-06-07 17:25 UTC, zrakhimov commented on content/docs/rendering-elements.md
> +Brauzer DOM elementlaridan farqli o'laroq, React elementlari oddiy obyektlar hisoblanadi va ularni yaratish juda arzonga tushadi. React DOM esa DOM ni React elementlariga mos ravishda yangilashni o'z
`ularni yaratish katta kompyuter resurslarini talab qilmaydi` bo'ladimi?

2021-06-07 17:35 UTC, zrakhimov commented on content/docs/rendering-elements.md
> +## Elementni DOM ga Chizish {#rendering-an-element-into-the-dom}
Ingliz tilida gi sarlovha konvensiyasi bo'yicha ko'p "ma'nosi" bor so'zlar katta harfda yozilgan ekan, rus tilidagisi boshqacha ekan. Shuni ham [kelishuv](https://github.com/reactjs/uz.reactjs.org/blob/master/TRANSLATION.md) ga qo'shib qo'yish qo'ysela yaxshi bo'lardi. 

Manimcha, `Elementni DOMga chizish` dan ko'ra `Elementni DOM ga Chizish` ko'zga yengilroq ko'rinadi sarlovha sifatida. Qisqartmadan keyin bo'sh joy qo'yish yoki yo'qligiga `bias` yo'q :) Shuni ham kelishuv ga yozib qo'yish kerekan, hammayoqda bir xil bo'ladi. Nima didiz?

2021-06-07 17:39 UTC, zrakhimov commented on content/docs/rendering-elements.md
> +Buni biz "ildiz" DOM tugunimiz deb ataymiz, chunki ichidagi hamma narsa React DOM orqali boshqariladi.
Mana shu joyida boshim qotuvdi, gapizga qo'shilaman. `O'zak DOM elementi` ham yaxshi fikr.

`Bu asosiy DOM elementi deyiladi, chunki ichidagi hamma narsa React DOM orqali boshqariladi` bo'ladimi?

2021-06-07 17:45 UTC, zrakhimov commented on content/docs/rendering-elements.md
> +React bilan qurilgan ilovalar odatda faqat bir dona ildiz DOM tuguni bo'ladi. Agar siz React ni boshqa ishlab turgan ilovaga biriktirmoqchi bo'lsangiz, siz bir nechta ildiz DOM tugunlarini yaratishin
`React bilan qurilgan ilovalar odatda faqat bir dona asosiy DOM elementi bo'ladi. Agar siz React ni boshqa ishlab turgan ilovaga biriktirmoqchi bo'lsangiz, siz bir biridan alohida bo'lgan bir nechta ildiz DOM tugunlarini yaratishingiz mumkin.` bo'ladimi?

2021-06-07 17:46 UTC, zrakhimov commented on content/docs/rendering-elements.md
> +React elementlari [o'zgarmas](https://en.wikipedia.org/wiki/Immutable_object) hisoblanadi. Bir marta yaratilgandan keyin, uni bolalari yoki atributlarini o'zgartirolmaysiz. Element kino lentasigadagi
shu so'zni topolmaganidim. 👍

2021-06-09 08:50 UTC, 0tabek16 commented on content/docs/rendering-elements.md
> +## Elementni DOM ga Chizish {#rendering-an-element-into-the-dom}
Fikringizga qoʻshilaman.

Daryo.uz stilida `'` qoʻshtirnoq qoʻysakchi biror atamadan soʻng? Masalan, `Elementni DOM'ga chizish`.

2021-06-09 08:51 UTC, 0tabek16 commented
@zrakhimov thank you for translations :)

2021-06-09 08:55 UTC, 0tabek16 commented
@turdiyev @umidbekk @Shoyadbek can you guys help with review?

2021-06-09 09:14 UTC, umidbekk commented
@doniyor2109 please help 🙂

2021-06-09 09:49 UTC, doniyor2109 requested changes

2021-06-09 09:49 UTC, doniyor2109 commented on content/docs/rendering-elements.md
> +Elementlar React ilovalarining eng kichik qurish bloklari hisoblanadi
```suggestion
Elementlar React ilovalarining eng kichik qurish bloklari hisoblanadi.
```

2021-06-09 09:49 UTC, doniyor2109 commented on content/docs/rendering-elements.md
> +React elementini ildiz DOM tuguniga uzatish uchun, bu ikkisini [`ReactDOM.render()`](/docs/react-dom.html#render) ni ichiga tashlang:
```suggestion
React elementini asosiy DOM elementi ichiga chizish uchun, bu ikkisini [`ReactDOM.render()`](/docs/react-dom.html#render) ichiga tashlang:
```

2021-06-09 09:49 UTC, doniyor2109 commented on content/docs/rendering-elements.md
> +React elementlari [o'zgarmas](https://en.wikipedia.org/wiki/Immutable_object) hisoblanadi. Bir marta yaratilgandan keyin, uni bolalari yoki atributlarini o'zgartirolmaysiz. Element kino lentasigadagi
```suggestion
React elementlari [o'zgarmas](https://en.wikipedia.org/wiki/Immutable_object) hisoblanadi. Bir marta yaratilgandan keyin, uni bolalari yoki atributlarini o'zgartirolmaysiz. Element kino lentasigadagi bir kadrga o'xshaydi: u ma'lum bir vaqtdagi UI ni tasvirlaydi.
```

2021-06-09 13:34 UTC, umidbekk submitted a review, later dismissed

2021-06-09 14:00 UTC, zrakhimov commented
Uzr @umidbekk , bir nechta suggest qilingan o'zgartirishlarni commit qildim. You can review now, I wont' touch it 👍🏻

2021-06-09 14:07 UTC, umidbekk approved these changes

2021-06-09 14:42 UTC, doniyor2109 approved these changes

2021-06-09 15:26 UTC, merged

2021-06-09 15:28 UTC, umidbekk commented
Thank you @zrakhimov !