Components and Props Translated
reactjs/uz.reactjs.org pull request #58
Opened 2021-06-21 05:50 UTC by zrakhimov

Hello 👋

Translated "Components and Props" section to Uzbek. Please review and let me know if any suggestions or questions.

Thanks!

![image](https://user-images.githubusercontent.com/22464933/122713049-13a9eb00-d233-11eb-9bcd-8cae3dfa68eb.png)

2021-06-22 13:02 UTC, zrakhimov commented
@doniyor2109 @umidbekk @turdiyev

2021-06-23 04:38 UTC, doniyor2109 requested changes

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Bundan oldin biz faqat HTML teglariga ega bo'lgan React elementlarini ko'rib chiqgan edik:
```suggestion
Bundan oldin biz faqat DOM teglariga ega bo'lgan React elementlarini ko'rib chiqgan edik:
```

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Agarda React dasturchi yaratgan komponentni element orqali uchratsa, JSX attributlari va bolalarini shu komponentga bir dona obyekt sifatida uzatadi. Biz bu obyektni "props" deb ataymiz.
```suggestion
Qachonki React dasturchi yaratgan komponentni element ko'rinishida uchratsa, JSX attributlari va bolalarini shu komponentga bir dona obyekt sifatida uzatadi. Biz bu obyektni "props" deb ataymiz.
```

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Masalan,`<div />` HTML div teg ni belgilaydi, lekin `<Welcome />` esa komponentni belgilaydi va kod qamrovida bo'lishini talab qiladi.
```suggestion
Masalan,`<div />` HTML div teg ni ifodalaydi, lekin `<Welcome />` esa komponentni ifodalaydi va `Welcome` ni shu kodning qamrovida bo'lishini talab qiladi.
```

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Bu esa `Comment` qismini bundanda soddalashtirishga imkon beradi:
```suggestion
Bu esa `Comment` ni bundanda soddalashtirishga imkon beradi:
```

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Komponentlarni ajratish boshida mayda ishga o'xshab tuyilishi mumkin, lekin katta ilovalarda qayta ishlatiladigan komponentlar to'plamiga ega bo'lish ko'p yengilliklar tug'diradi. Agarda sizning UI'i
```suggestion
Komponentlarni ajratish boshida mayda ishga o'xshab tuyilishi mumkin, lekin katta ilovalarda qayta ishlatiladigan komponentlar to'plamiga ega bo'lish ko'p yengilliklarni yaratadi. Agarda sizning UI'ingizdagi qaysidir bo'lak bir necha marta ishlatiladigan bo'lsa (`Button`, `Panel`, `Avatar`) yoki o'z o'zidan murakkab bo'lsa (`App`, `FeedStory`, `Comment`), shu bo'lakni komponentga ajratish yaxshi nomzod bo'ladi. 
```

2021-06-23 04:38 UTC, doniyor2109 commented on content/docs/components-and-props.md
> +Albatta, ilova UI'lari dinamik hisoblanadi va vaqt o'tgan sari o'zgarishi mumkin. [Keyingi bo'limda](/docs/state-and-lifecycle.html), biz "holat" (state) mavzusiga kirish qilamiz. Holat React kompone
```suggestion
Albatta, ilova UI'lari dinamik hisoblanadi va vaqt o'tgan sari o'zgarishi mumkin. [Keyingi bo'limda](/docs/state-and-lifecycle.html), biz "holat" (state) tushunchasi bilan tanishib chiqamiz. Holat React komponentlariga vaqt o'tgan sari foydalanuvchi harakatlari, tarmoq javoblari, va boshqa holatlar orqali bu qoidani buzmagan holda reaksiya qilib o'zining qaytarmalarini o'zgartirishga imkon beradi.
```

2021-06-23 12:32 UTC, zrakhimov commented
Thanks @doniyor2109  for the suggestions! I'm good with them.

2021-06-23 12:41 UTC, umidbekk approved these changes

2021-06-23 12:42 UTC, umidbekk commented
@zrakhimov thank you for yet another contribution :)

2021-06-23 12:42 UTC, merged