state-and-lifecycle page translated
reactjs/uz.reactjs.org pull request #60
Opened 2021-08-12 08:23 UTC by MRXDeveloper23

2021-08-14 15:30 UTC, doniyor2109 requested changes

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Bu sahifa React komponentidagi holat(state) va hayotiy ketma-ketlik(lifecycle) tushunchalarini tanishtiradi.Bu yerda [batafsil API komponentiga havolani](/docs/react-component.html) topa olasiz.
```suggestion
Bu sahifa React komponentidagi holat(state) va hayotiy ketma-ketlik(lifecycle) tushunchalarini tanishtiradi.Bu yerda [batafsil komponentinig API ma'lumotnomasini](/docs/react-component.html) topa olasiz.
```

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +[Oldingi bo'limlarning bir namunasidagi](/docs/rendering-elements.html#updating-the-rendered-element) soatga e'tibor bering. [Elementlarni chizishda](/docs/rendering-elements.html#rendering-an-elemen
```suggestion
[Oldingi bo'limlarning namunalardan biridagi](/docs/rendering-elements.html#updating-the-rendered-element) soatga e'tibor bering. [Elementlarni chizish](/docs/rendering-elements.html#rendering-an-element-into-the-dom) bo'limida, biz faqat foydalanuvchi interfeysini(UI) yangilashni bir yo'lini o'rgandik. Biz chizilgan natijani o'zgartirish uchun `ReactDOM.render()`ni chaqiramiz:
```

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Bu bo'limda, biz qanday qilib `Clock` komponentini rostdan ham qayta ishlaydigan va jamlangan qilishni o'rganamiz. Soat komponenti hozirgi vaqtni o'rnatadi va har sekundda o'zini yangilaydi.
```suggestion
Bu bo'limda, biz qanday qilib `Clock` komponentini rostdan ham qayta ishlaydigan va jamlangan qilishni o'rganamiz. Soat komponenti o'zinig taymerini o'rnatadi va har sekundda o'zini yangilaydi.
```

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Ammo, u muhim talabni bajarmadi: bu fakt shuki `Clock` taymerni o'rnatadi va foydalanuvchi interfeysini har soniyada yangilaydi, bu `Clock` ning amalga oshirish tafsilotlari bo'lishi kerak.
```suggestion
Ammo, u muhim talabni bajarmadi: bu fakt shuki taymerni o'rnatish va foydalanuvchi interfeysini har soniyada yangilashini `Clock` komponenti o'zi amalga oshirish kerak.
```

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Siz `Clock` o'xshash funksional komponentni besh qadamda klass komponentiga aylantira olasiz:
Please use "funksiyaviy komponent" term (see  [TRANSLATION.md](https://github.com/reactjs/uz.reactjs.org/blob/main/TRANSLATION.md#:~:text=function%20component) file)

2021-08-14 15:30 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Siz `Clock` o'xshash funksional komponentni besh qadamda klass komponentiga aylantira olasiz:
```suggestion
Siz `Clock` ga o'xshash funksiyaviy komponentni besh qadamda klass komponentiga aylantira olasiz:
```

2021-08-14 15:31 UTC, doniyor2109 commented
@MRXDeveloper23 Thanks for your help. I have reviewed some files. It seems to be many changes. I will review others soon. Thanks

2021-08-15 01:19 UTC, doniyor2109 requested changes

2021-08-15 01:19 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +4. `render()` metodi tanasidagi `props` parameterdan olingan o'zgaruvchini `this.props` bilan o'zgartiring.
```suggestion
4. `render()` metodi tanasidagi `props` o'zgaruvchini `this.props` bilan o'zgartiring.
```

2021-08-15 01:19 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +5. Qolgan bo'sh funksiya chaqiruvlarini o'chiring.
```suggestion
5. Qolgan bo'sh funksiyani o'chiring.
```

2021-08-15 01:19 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Biz `date` xususiyatini kiritmalardan(props) holatga(state) uch qadamda ko'chiramiz:
Do we need `xususiyatini` here?

2021-08-15 07:54 UTC, doniyor2109 requested changes

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Ko'p komponentlarga ega ilovalarda, komponentlar yo'q qilinganda ular tomonidan olingabn joy va resurslarni
```suggestion
Ko'p komponentlarga ega ilovalarda, komponentlar yo'q qilinganda ular tomonidan olingan resurslarni
```

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Biz komponent o'rnatilganda(mount) va tozalanganda(unmount) biror kod bajarish uchun klass komponentida maxsus metodlarni e'lon qilishimiz mumkin:
Please use `yechish` for `unmount` [see](https://github.com/reactjs/uz.reactjs.org/blob/main/TRANSLATION.md#:~:text=(un)mount)

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +`componentDidMount()` metodi komponent natijasi DOMga chizilgandan keyin ishlaydi. Bu taymer o'rnatish uchun juda yacshi joy:
```suggestion
`componentDidMount()` metodi komponent natijasi DOMga chizilgandan keyin ishlaydi. Bu taymer o'rnatish uchun juda yaxshi joy:
```

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +`this.props` React o'zi tomonidan o'rnatilgan va `this.state` maxsus ma'noga ega paytda, agar siz ma'lumot oqimida qatnashmaydigan narsalarni (masalan, taymer identifikatori) saqlashingiz kerak bo'ls
```suggestion
`this.props` React o'zi tomonidan o'rnatilgan va `this.state` maxsus ma'noga ega. Agar siz ma'lumot oqimida qatnashmaydigan narsalarni (masalan, taymer identifikatori) saqlashingiz kerak bo'lsa, siz qo'lda klassga qo'shimcha maydonlarni qo'shishingiz mumkin..
```

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +1) `<Clock />` komponenti `ReactDOM.render ()` ga o'tkazilganda, React `Clock` komponentining konstruktorini chaqiradi. `Clock` joriy vaqtni ko'rsatishi kerak bo'lganligi sababli, u "this.state" ni j
```suggestion
1) `<Clock />` komponenti `ReactDOM.render()` ga o'tkazilganda, React `Clock` komponentining konstruktorini chaqiradi. `Clock` joriy vaqtni ko'rsatishi kerak bo'lganligi sababli, u "this.state" ni joriy vaqtni o'z ichiga olgan ob'ekt bilan boshlaydi. Keyinchalik bu holatni yangilaymiz.
```

2021-08-15 07:54 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +4) Har soniyada brauzer `tick()` metodini chaqiradi. Uning ichida `Clock` komponenti joriy vaqtni o'z ichiga olgan ob'ekt bilan `setState()`ni chaqirib, UI yangilanishini rejalashtiradi. `SetState()`
```suggestion
4) Har soniyada brauzer `tick()` metodini chaqiradi. Uning ichida `Clock` komponenti joriy vaqtni o'z ichiga olgan ob'ekt bilan `setState()`ni chaqirib, UI yangilanishini rejalashtiradi. `setState()` chaqiruvi tufayli React holat o'zgarganini biladi va ekranda nima bo'lishi kerakligini bilish uchun `render()` usulini qayta chaqiradi. Bu safar `render()` usulidagi `this.state.date` har xil bo'ladi, shuning uchun renderning qaytargan natijasi yangilangan vaqtni o'z ichiga oladi. React DOMni shunga mos ravishda yangilaydi.
```

2021-08-28 13:32 UTC, doniyor2109 commented
@MRXDeveloper23 Hello. What is the state of this PR? Do you need any help?

2021-09-23 16:10 UTC, doniyor2109 requested changes

2021-09-23 16:10 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Biz komponent o'rnatilganda(mount) va tozalanganda(unmount) biror kod bajarish uchun klass komponentida maxsus metodlarni e'lon qilishimiz mumkin:
```suggestion
Biz komponent o'rnatilganda(mount) va yechilganda(unmount) biror kod bajarish uchun klass komponentida maxsus metodlarni e'lon qilishimiz mumkin:
```

2021-09-23 16:16 UTC, doniyor2109 requested changes

2021-09-23 16:16 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Qnaday qilib `props`ni asosiy konstruktorga o'tkazganimizni eslab qoling:
```suggestion
Qnaday qilib `props`ni asosiy konstruktorga o'tkazganimizga etibor bering:
```

2021-09-23 16:16 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +bo'shatish juda muhim.
```suggestion
Ko'p komponentlarga ega ilovalarda, komponentlar yo'q qilinganda ular tomonidan olingan resurslarni bo'shatish juda muhim.
```

2021-09-23 16:16 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Komponent lokal holatiga yangilanishlarni rejalashtirish uchun u `this.setState ()` dan foydalanadi:
```suggestion
Komponent lokal holatiga yangilanishlarni rejalashtirish uchun u `this.setState()` dan foydalanadi:
```

2021-10-08 11:48 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +Biz `date` xususiyatini kiritmalardan(props) holatga(state) uch qadamda ko'chiramiz:
```suggestion
Biz `date`ni kiritmalardan(props) holatga(state) uch qadamda ko'chiramiz:
```

2021-10-08 11:51 UTC, doniyor2109 commented on content/docs/state-and-lifecycle.md
> +React ilovalarida komponentning holatli yoki holatsiz ekanligi vaqt o'tishi bilan o'zgarishi mumkin bo'lgan komponentni amalga oshirish tafsiloti hisoblanadi. Holatsiz bo'lgan komponentlarni holatli
```suggestion
React ilovalarida komponentning holatli yoki holatsiz ekanligi komponentni amalga oshirish tafsiloti hisoblanadi va bu vaqt o'tishi bilan o'zgarishi mumkin. Holatsiz bo'lgan komponentlarni holatli komponentlar ichida ishlatishingiz mumkin va aksincha.
```

2021-10-08 11:58 UTC, doniyor2109 approved these changes

2021-10-08 12:00 UTC, merged

2021-10-08 12:04 UTC, zrakhimov commented
O'ziz update qilib qo'yaqopsizde