Translated "Lists and keys" page
reactjs/uz.reactjs.org pull request #63
Opened 2021-09-17 12:39 UTC by 0tabek16

Salom qadrli maintainerlar 👋

Bu PRʼda `lists-and-keys.md` fayli tarjima qilindi.

Koʻz yugurtirib chiqishingizni iltimos qilgan bo'lar edim.

2021-09-23 16:07 UTC, doniyor2109 requested changes

2021-09-23 16:07 UTC, doniyor2109 commented on content/docs/lists-and-keys.md
> +Keling, avval roʻyxatlarni JavaScriptʼda qanday oʻzgartirishni koʻramiz.
`JavaScriptʼda` shu yerda `ʼ`  bu belgini olib tashlasak dima deysiz?

2021-09-23 16:07 UTC, doniyor2109 commented on content/docs/lists-and-keys.md
> +JSX [hohlagan ifodani](/docs/introducing-jsx.html#embedding-expressions-in-jsx) jingalak qavslar ichiga joylashga ruhsat beradi va `map()` qaytargan javobni bir qatorda yozib keta olamiz:
```suggestion
JSX [hohlagan ifodani](/docs/introducing-jsx.html#embedding-expressions-in-jsx) jingalak qavslar ichiga joylashga ruxsat beradi va `map()` qaytargan javobni bir qatorda yozib keta olamiz:
```

2021-09-24 05:38 UTC, 0tabek16 commented on content/docs/lists-and-keys.md
> +Keling, avval roʻyxatlarni JavaScriptʼda qanday oʻzgartirishni koʻramiz.
Tutuq belgisini boshqa tilda yozilgan soʻzni ajralib turishi uchun ishlatgandim. Bemalol olib tashlashim mumkin.

2021-09-24 15:13 UTC, doniyor2109 commented on content/docs/lists-and-keys.md
> +Keling, avval roʻyxatlarni JavaScriptʼda qanday oʻzgartirishni koʻramiz.
Ha tushunarliroq bo'lar ekan ammo qolgan sahifalardagi tarjimalarda bunday uslub ishlatilmaganligi uchun, olib tashlash to'g'ri deb o'ylayman. 

Nima deysiz?

2021-09-24 15:23 UTC, 0tabek16 commented on content/docs/lists-and-keys.md
> +Keling, avval roʻyxatlarni JavaScriptʼda qanday oʻzgartirishni koʻramiz.
Yaxshi fikr, o'zgartirib qo'ydim.

2021-09-25 09:43 UTC, doniyor2109 approved these changes, later dismissed

2021-09-25 09:55 UTC, doniyor2109 commented
@netlify_bot deploy

2021-09-25 09:59 UTC, doniyor2109 commented
@netlify deploy

2021-09-25 10:03 UTC, doniyor2109 commented
@netlify deploy

2021-09-25 10:04 UTC, doniyor2109 commented on content/docs/lists-and-keys.md
> +[**CodePenʼda ochish**](https://codepen.io/gaearon/pen/BLvYrB?editors=0010)
```suggestion
[**CodePenda ochish**](https://codepen.io/gaearon/pen/BLvYrB?editors=0010)
```

2021-09-26 07:12 UTC, doniyor2109 commented
@umidbekk Netlify deploy is hanging up some how. Can we merge it without it?

2021-09-26 08:56 UTC, umidbekk commented
> @umidbekk Netlify deploy is hanging up some how. Can we merge it without it?

@doniyor2109 I've changed required check from netlify to vercel

2021-09-26 10:24 UTC, doniyor2109 approved these changes

2021-09-26 10:24 UTC, merged