Getting started page
reactjs/uz.reactjs.org pull request #80
Opened 2022-10-16 05:25 UTC by Zokirkhon1002

2022-10-16 05:27 UTC, Zokirkhon1002 commented
Translated Getting-started-page

2022-10-17 07:25 UTC, doniyor2109 requested changes

2022-10-17 07:25 UTC, doniyor2109 commented on content/community/nav.yml
>        title: Support
`title` ni ham tarjimaga qo'shsak bo'ladimi?

2022-10-17 07:25 UTC, doniyor2109 commented on src/templates/components/NavigationFooter/NavigationFooter.js
> -                <SecondaryLabel>Next article</SecondaryLabel>
`Previous article` ni ham tarjima qila olasizmi?
https://github.com/reactjs/uz.reactjs.org/pull/80/files#diff-9eb004a9d63a682485a443edf49a4b0363b96cb40bfed5423e1676223abecea5L43

2022-10-18 03:43 UTC, Zokirkhon1002 commented on src/templates/components/NavigationFooter/NavigationFooter.js
> -                <SecondaryLabel>Next article</SecondaryLabel>
vaqt ajratishim bilan qilib qo'yaman

2022-10-21 16:26 UTC, closed without merging